version: '3.8'

services:

  mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "spring_batch"
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "9000:8080"